version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/jiangzx
hooks:
  BeforeInstall:
    - location: scripts/stop-process.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start-process.sh
      timeout: 300
      runas: ec2-user
