version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/jiangzx
hooks:
  BeforeInstall:
    - location: 
      timeout: 300
      runas: root
  AfterInstall:
    - location: 
      timeout: 300
      runas: root
